### PR TITLE
Update all project deps + BONUS add temp favicon

### LINKED ISSUE #22: Update all dependencies

### PR DESCRIPTION
**Pull request by BeckyPollard**
### RE: [Update all dependencies](https://github.com/badgateway/tt-app/issues/22)
Resolves #22.

## Summary of changes:
- Update all project deps.
- Bonus: add a temp favicon to the webpage. ⏱
  - Favicon inspo: [Lea Verou](https://twitter.com/LeaVerou/status/1241619866475474946)

qubyChan-v

### CODE REVIEW

**Comment by BeckyPollard** [comment]
**WELLP** now i understand what "auto-merge" does, i thought it would wait for a passing review lmao.

**Comment by evert** [comment]
@BeckyPollard it only does that if we tell github to require 'at least 1 review', which we can do!

**Comment by evert** [comment]
I just set this up

**Comment by pschwyter** [comment]
lol 🚢 !

**Pull request merged**
